wosMenu<-sidebarMenu(
  menuItem('Bibliography', 
           tabName = 'tabItemBibs', 
           icon = icon('database')),
  menuItem('Data', 
           tabName = 'bibDT', 
           icon = icon('book'), 
           startExpanded = TRUE,
           menuSubItem('Import', tabName = 'tabItemLibraryImport'),
           menuSubItem('Journals', tabName = 'tabItemJournals'),
           menuSubItem('Authors', tabName = 'tabItemResearchers')
  ),
  menuItem('Analysis', 
           tabName = 'analysis', 
           icon = icon('bar-chart-o'),
           startExpanded = T,
           menuSubItem('Keywords', tabName = 'tabItemKeywordsAnalysis'),
           menuSubItem('Topics', tabName = 'tabItemTopicAnalysis')
  ),
  menuItem('About', 
           tabName = 'tabItemAbout', 
           icon = icon('question-circle')) )

bibFilterPanel<-conditionalPanel(condition="input.hideFilter == false",
                                 fluidRow(column(2,
                                                 checkboxInput("checkKeyWords", "With key words"),
                                                 checkboxInput("checkAbstract", "With abstracts"),
                                                 checkboxInput("checkFullText", "Full text"),
                                                 textInput("Authors", "Enter author`s names", value = "")),
                                          column(3,
                                                 sliderInput("sliderYear", 
                                                             "Year`s range", 
                                                             min = g$year$min, max = g$year$max,
                                                             step = 1, round = 0,
                                                             value = c(g$year$max-5,g$year$max)),
                                                 sliderInput("sliderJscore", 
                                                             "Journal score",
                                                             min =g$jscore$min, max = g$jscore$max,
                                                             step = .1, round = 2,
                                                             value = c(1,g$jscore$max))
                                          ),
                                          column(3,
                                                 sliderInput("sliderAscore", 
                                                             "Author`s score", 
                                                             min =g$ascore$min, max = g$ascore$max,
                                                             step = .1, round = 2,
                                                             value = c(0,g$ascore$max)),
                                                 sliderInput("sliderNrecords", 
                                                             "Author`s number of records",
                                                             min =g$nrecords$min, max = g$nrecords$min,
                                                             step = 1, round = 0,
                                                             value = c(1,g$nrecords$min))
                                          ),
                                          column(4,
                                                 selectInput("Journal", 
                                                             "Journals", 
                                                             choices = g$journals, 
                                                             selected = "All"),
                                                 selectInput("Publisher", 
                                                             "Publishers", 
                                                             choices = g$publishers, 
                                                             selected = "All"))),
                                 shiny::tags$div(class="header", checked=NA,
                                                 shiny::tags$p("Search in...")),
                                 fluidRow(column(3,
                                                 textAreaInput("searchKeyWords", "key words", "")),
                                          column(3,
                                                 textAreaInput("searchTitle", "title", "")),
                                          column(3,
                                                 textAreaInput("searchAbstract", "abstract", "")),
                                          column(3,
                                                 textAreaInput("searchFullText", "full text", ""))),
                                 fluidRow(column(3, 
                                                 downloadButton("openPDFMain", "Open selected .pdf from table below")),
                                          column(3,
                                                 actionButton("deleteSelectedFromMainDB", "Delete selected records")),
                                          column(3,
                                                 actionButton("resetSelectionInMainDB", "Reset selection"))))

checkBibReferencesPanel<-conditionalPanel(condition="input.hideCheckReferencesPanel == false",
                                 fluidRow(column(2,checkboxInput("checkShowDuplicates", "Show Duplicates")),
                                          column(2, actionButton("deleteDuplicates", "Delete duplicates")),                                          
                                          column(2, actionButton("checkReferences", "Check References")) ))

bibExportPanel<-fluidRow(column(4,
                                actionButton("addSelected", "Add selected records to export table"),
                                br(),br(),
                                actionButton("removeSelected", "Remove selected record from export table"),
                                br(),br(),
                                downloadButton("openPDF", "Open selected .pdf from table below")),
                         column(4,
                                actionButton("addExportFolder", "Add export folder"), 
                                actionButton("deleteExportFolder", "Delete export folder"),
                                textInput("newExportFolder", "New export folder"),
                                actionButton("loadBibs", "Load records"),
                                actionButton("exportBibs", "Export records")),
                         column(4,
                                selectInput("exportFolders", "Research paper folder:", 
                                            choices=g$export$folders, 
                                            selected =g$export$folder),
                                selectInput("exportFileFormats", "File formats", 
                                            choices = g$export$fileFormats, 
                                            selected =g$export$fileFormat)))
tabBibs<-tabItem(tabName="tabItemBibs",
        bibFilterPanel,
        checkBibReferencesPanel,
        fluidRow(column(3,checkboxInput("hideFilter", "Hide/Show Filter Panel")),
                 column(3,checkboxInput("hideCheckReferencesPanel", "Hide/Show Check References Panel", value = T)),
                 column(3,actionButton("applyFilter", "Apply Filter")),
                 column(3,actionButton("resetFilter", "Reset Filter"))),
        fluidRow(box(DT::dataTableOutput('tableBibs'),
                     'Bibliography records from research journals, select to export...',
                     width = 12, solidHeader = T),
                 width=12),
        fluidRow(tabBox(title = "Selected bibliography record",
                        id="tabSelectedBibRecord", 
                        width = 12,
                        tabPanel("APA style",
                                 htmlOutput("cur_bib")),
                        tabPanel("Bibtex format",
                                 htmlOutput("cur_bibtex")))),
        bibExportPanel,
        fluidRow(tabBox(title = "Selected bibliography records",
                        width=12,
                        tabPanel("Table",
                                 DT::dataTableOutput('tableBibsExport'),
                                 'Bibliography records from research journals, select to export...'),
                        tabPanel("Bibtex",
                                 htmlOutput("cur_bibtex_multy")),
                        tabPanel("RMarkdown",
                                 htmlOutput("cur_bibtex_rmarkdown")),
                        tabPanel("RMarkdown with text chunks",
                                 fluidRow(
                                   column(3,actionButton("suggestTerms", "Suggest Terms"),br(),br(),
                                          actionButton("get_text_chunks", HTML("Get RMarkdown<br/>with text chunks"),
                                                       style="white-space: normal;
                                                        text-align:center;
                                                       height:50px;
                                                       width:150px;
                                                       font-size: 14px;")),
                                   column(6,textAreaInput("termsToFindInFullTexts","Search Terms in Full Texts",
                                                          width = 600, rows = 4))),
                                 htmlOutput("text_chunks_with_terms")) )),
        fluidRow(tabBox(title = "Selected bibliography record",
                        id="tabSelectedBibRecordForExport", 
                        width = 12,
                        tabPanel("APA style",
                                 htmlOutput("cur_bibExport")), 
                        tabPanel("Bibtex format",
                                 htmlOutput("cur_bibtexExport"))))
)
tabResearchers<-tabItem(tabName="tabItemResearchers",
                        fluidRow(box(actionButton("loadResearchers", "Load researchers"),
                                     width = 12)),
                        fluidRow(box('Top researchers Clarivate Analytics',
                                     DT::dataTableOutput('tableResearchers'),
                                     width = 12, solidHeader = T),
                                 width=12),
                        fluidRow(box('Top researchers by year',
                                     DT::dataTableOutput('tableTopResearchersByYear'),
                                     width = 12, solidHeader = T),
                                 width=12),
                        fluidRow(box('Verbose researchers by year',
                                     DT::dataTableOutput('tableVerboseResearchersByYear'),
                                     width = 12, solidHeader = T),
                                 width=12))
tabJournals<-tabItem(tabName="tabItemJournals",
                     fluidRow(box(actionButton("loadJscores", "Load journal cite score metrics"),
                                  width = 12)),
                     fluidRow(box('Scopus journals cite score metrics',
                                  DT::dataTableOutput('tableJournals'),
                                  width = 12, solidHeader = T),
                              width=12) )
tabLibraryImport<-tabItem(tabName="tabItemLibraryImport",
                        fluidRow(box(actionButton("importResearchPapers", "Import research papers"),
                                     actionButton("computeStatistics", "Compute statistics"),
                                     actionButton("getBibEntryWithDOI", "Get bib entries for downloaded .pdf files"),
                                     checkboxInput("deleteSourcePDFs", "Delete source .pdf files", value=F),
                                     width = 12)),
                        fluidRow(box("Publishers statistics",
                                     DT::dataTableOutput('tablePublisherStat'),
                                     width = 12, solidHeader = T),
                                 width=12),
                        fluidRow(column(4,
                                        selectInput("separateJournal", 
                                                    "Select journal to show statistics for...",
                                                    choices = g$journals[-1]))),
                        fluidRow(box("Separate journal statistics (#full text records/#abstracts/#bib records)",
                                     DT::dataTableOutput('tableSeparateJournalStat'),
                                     width = 12, solidHeader = T)),
                        fluidRow(box("Whole library statistics (Full text/Abstract/Total)",
                                     DT::dataTableOutput('tableWholeLibraryStat'),
                                     width = 12, solidHeader = T),
                                 width=12))
tabKeywordsAnalysis<-tabItem(tabName = "tabItemKeywordsAnalysis",
                             fluidRow(box(actionButton("computeKeyWordsFrequencies", "Compute key word frequencies"),
                                          width = 12)),
                             fluidRow(
                               tabBox(title = "Word frequencies",
                                      id="tabWordFrequencies", 
                                      width = 12,
                                      tabPanel("Key word modified scores by year",
                                               "Key word modified scores by year",
                                                   DT::dataTableOutput('tableKeyWordMscore'),
                                               "Key word modified scores for all selected records",
                                                   plotOutput("plotKeyWordMscore")),
                                      tabPanel("Key words frequencies",
                                                   DT::dataTableOutput('tableKeyWordFrequencies'),
                                               "Key word frequencies for all selected records",
                                                   plotOutput("plotKeyWordFrequencies"))
                                      )))

tabTopicAnalysis<-tabItem(tabName = "tabItemTopicAnalysis",
                  fluidRow(box(actionButton("startTopicAnalysis", "Start topic analysis"),
                               actionButton("showTopicAnalysisResults", "Show Topic Analysis Results"),
                               width = 12)),
                  fluidRow(box("Topic analysis results",
                               DT::dataTableOutput('tableTopicModelSummary'),
                               width = 12, solidHeader = T)),
                  fluidRow(box(plotOutput("plotTopicModelDendrogram"),
                               width = 12)),
                  fluidRow(box("Topic models coherence matrix",
                               plotOutput("plotTopicModelCoherence"),
                               width = 12)) )
tabAbout<-tabItem(tabName = "tabItemAbout",
                  fluidRow(title = "About Web of science reference manager",
                           column(4), 
                           column(4,
                                  shiny::span(shiny::tagList(shiny::tags$img(src='wos-logo.png',
                                                                             height='45',
                                                                             width='125'))))),
                  fluidRow(column(2), 
                           column(8, box(width=12, paste("Bibliography manager. <br/>
                               This shiny application allows to import, organize, manage and export bibiliography references in .bibtex format (JabRef) and in RMarkdown reference format together with corresponding fulltexts in .pdf format.
                                         <br/> © Borochkin A.A.,", year(Sys.Date())) %>% HTML)),
                           column(2)),
                  fluidRow(column(2, actionButton("checkForUpdates", "Check for updates")),
                           column(5, textInput("sourcePath", "Source path:", value=g$path$source)),
                           column(5, textInput("destinationPath", "Destination path:", value =g$path$destination))))